### ISSUE TITLE
 McAfee Endpoint Security identified as phishing page

### ISSUE THREAD

**Issue by rsrini7** [firmai/awesome-google-colab#1]
Why McAfee identified as phishing page ?  https://www.google-colab.com/

![2020-05-13 15_01_46-Window](https://user-images.githubusercontent.com/5178105/81796308-e3b9ef80-952a-11ea-979b-ef3389207641.png)

**Comment by zach67385** [comment]
It is a phishing page. You should always visit https://colab.research.google.com!
